PROGRAM ARRAYSPRAC
IMPLICIT NONE

INTEGER :: N
! INTEGER, DIMENSION(N) :: ONE, TWO, THREE

PRINT *, 'ENTER THE LENGTH OF THE ARRAY = >'
READ *, N


IF(ABS(N) > 0) THEN
  CALL SETARRAY(N)
ELSE IF(N /= 0) THEN
  PRINT *, 'YOU HAVE ENTERED AN INVALID INPUT. PLEASE, TRY AGAIN!'
END IF

END PROGRAM ARRAYSPRAC

! FUNCTION CALELEMENT (ARR, N)
!   INTEGER, DIMENSION(N) :: ARR, SUM
!   INTEGER, DIMENSION(4) :: CALELEMENT

! END FUNCTION CALELEMENT

SUBROUTINE SETARRAY(N)
  IMPLICIT NONE

  INTEGER :: I, N

  INTEGER, DIMENSION(N) :: X, Y, SUM

  ! PRINT *, 'ENTER CONSECUTIVELY THE FOUR NUMBERS TO BE STORED'
  ! READ *, A1, A2, A3, A4
  ! PRINT *, 'ENTER CONSECUTIVELY THE FOUR NUMBERS TO BE STORED'
  ! READ *, B1, B2, B3, B4

  ! DO I=1, 4
  !   PRINT *, 'ENTER CONSECUTIVELY THE FIRST FOUR ELEMENTS'
  !   READ *, X(I)
  ! END DO

  ! DO I=1, 4
  !   PRINT *, 'ENTER CONSECUTIVELY THE SECOND FOUR ELEMENTS'
  !   READ *, Y(I)
  ! END DO

  DO I=1, 4
    PRINT *, 'ENTER CONSECUTIVELY FOUR ELEMENTS OF EACH ARRAY'
    READ *, X(I), Y(I)
  END DO

  PRINT *, 'SUMMING THE CORRESPONDING ELEMENTS IN EACH ARRAY'
  DO I = 1, 4
    PRINT *, 'THE SUM OF ELEMENTS IN FIRST AND SECOND ARRAY IN INDEX ', I, ' => ', X(I) + Y(I) 
    SUM(I) = X(I) + Y(I)
  END DO

  PRINT *, 'FIRST ARRAY ELEMENT IS => ', X
  PRINT *, 'SECOND ARRAY ELEMENT IS => ', Y
  PRINT *, 'THE SUM OF EACH CORRESPONDING ARRAY ELEMENT IS => ', SUM
END SUBROUTINE SETARRAY
