PROGRAM QUE2A
IMPLICIT NONE

REAL :: R, ANSWER
CHARACTER(LEN = 1) :: CHOICE

PRINT *, 'WHAT WOULD YOU LIKE TO DO?'
PRINT *, 'C => CIRCUMFERENCE'
PRINT *, 'A => AREA'
PRINT *, 'D => DIAMETER'

READ *, CHOICE

PRINT *, 'ENTER THE VALUE FOR R (RADIUS)'
READ *, R

CALL CHOICESELECTOR(CHOICE, ANSWER, R)

PRINT *, 'The result for your choice is => ', ANSWER

END PROGRAM QUE2A


REAL FUNCTION AREA(R)
  REAL :: ANSWER, R
  REAL :: PI = 3.14159
  
  PRINT *, 'CALCULATING AREA...'
  ANSWER = PI * R * R
  
  AREA = ANSWER
END FUNCTION AREA

REAL FUNCTION CIRCUMFERENCE(R)
  REAL :: ANSWER, R
  REAL :: PI = 3.14159

  PRINT *, 'CALCULATING CIRCUMFERENCE...'
  ANSWER = 2 * PI * R
  
  CIRCUMFERENCE = ANSWER
END FUNCTION CIRCUMFERENCE

REAL FUNCTION DIAMETER(R)
  REAL :: R

  ANSWER = 2.0 * R

  DIAMETER = ANSWER
END FUNCTION DIAMETER

SUBROUTINE CHOICESELECTOR(CHOICE, ANSWER, R)
  REAL :: ANSWER, R
  CHARACTER(LEN = 1) :: CHOICE

  IF (CHOICE == 'A' .OR. CHOICE == 'a') THEN
    ! AREA
    ANSWER = AREA(R)
  ELSE IF (CHOICE == 'C' .OR. CHOICE == 'c') THEN
    ! CIRCUMFERENCE
    ANSWER = AREA(R)

  ELSE IF(CHOICE == 'D' .OR. CHOICE == 'd') THEN
    ANSWER = DIAMETER(R)
  ELSE
    PRINT *, 'You have entered and invalid option'
  END IF

END SUBROUTINE CHOICESELECTOR
